// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGr-ngOOIH_4HIkDmQsjsCYpC9a4HJzg0',
    appId: '1:778335429824:web:1d66f860e09efdce987925',
    messagingSenderId: '778335429824',
    projectId: 'cumple-3ae2a',
    authDomain: 'cumple-3ae2a.firebaseapp.com',
    storageBucket: 'cumple-3ae2a.firebasestorage.app',
    measurementId: 'G-CEY5VG29X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmbpf0snBpl-y-NH06iiAdUv8RyCLtaM',
    appId: '1:778335429824:android:b51c108026cf7e16987925',
    messagingSenderId: '778335429824',
    projectId: 'cumple-3ae2a',
    storageBucket: 'cumple-3ae2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzLudT-Vpoq0DeH3ua6h5BEjVZ3GZSuaI',
    appId: '1:778335429824:ios:a7842b5e0ebc93f0987925',
    messagingSenderId: '778335429824',
    projectId: 'cumple-3ae2a',
    storageBucket: 'cumple-3ae2a.firebasestorage.app',
    iosBundleId: 'com.example.birthday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzLudT-Vpoq0DeH3ua6h5BEjVZ3GZSuaI',
    appId: '1:778335429824:ios:a7842b5e0ebc93f0987925',
    messagingSenderId: '778335429824',
    projectId: 'cumple-3ae2a',
    storageBucket: 'cumple-3ae2a.firebasestorage.app',
    iosBundleId: 'com.example.birthday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGr-ngOOIH_4HIkDmQsjsCYpC9a4HJzg0',
    appId: '1:778335429824:web:84311b6fce78ea4e987925',
    messagingSenderId: '778335429824',
    projectId: 'cumple-3ae2a',
    authDomain: 'cumple-3ae2a.firebaseapp.com',
    storageBucket: 'cumple-3ae2a.firebasestorage.app',
    measurementId: 'G-69NRWPEEPF',
  );
}
